CREATE DATABASE bdPartidoPTC

USE bdPartidoPTC

SELECT * FROM FiliadosPTC


SELECT COUNT (NUMERO_DA_INSCRICAO)FROM FiliadosPTC

--1
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'

--2
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE NOME_DO_FILIADO LIKE '%Sebastião'

--3
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE NOME_DO_FILIADO LIKE 'OS%'

--4
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO  FROM FiliadosPTC
WHERE NOME_DO_MUNICIPIO LIKE 'SÃO FÉLIX'

--5
SELECT NOME_DO_MUNICIPIO, NOME_DO_FILIADO  FROM FiliadosPTC
WHERE NOME_DO_MUNICIPIO LIKE 'INHAMBUPE'

--6
SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%'

--7
SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
WHERE NOME_DO_MUNICIPIO LIKE 'E%'

--8
SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
WHERE NOME_DO_MUNICIPIO LIKE '%CRUZ%'

--9
SELECT NOME_DO_MUNICIPIO FROM FiliadosPTC
WHERE NOME_DO_MUNICIPIO LIKE '%DE%'

--10
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE DATA_DA_FILIACAO BETWEEN '01-01-1990' AND '01-01-2000'

--11
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE DATA_DA_FILIACAO BETWEEN '02-01-2010' AND '01-03-2010'

--12
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE DATA_DA_FILIACAO BETWEEN '01-07-2007' AND '31-12-2007'

--13
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE SITUACAO_DO_REGISTRO LIKE 'REGULAR%'

--14
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE ZONA_ELEITORAL LIKE '203'

--15
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE ZONA_ELEITORAL LIKE '180'

--16
SELECT NOME_DO_FILIADO FROM FiliadosPTC
WHERE ZONA_ELEITORAL LIKE '199' 

--17
SELECT ZONA_ELEITORAL FROM filiadosPTC
ORDER BY ZONA_ELEITORAL ASC

--18

--19
UPDATE FiliadosPTC
SET SIGLA_DO_PARTIDO = 'PT'
WHERE CODIGO_DO_MUNICIPIO = 36471

--20
UPDATE FiliadosPTC
SET SIGLA_DO_PARTIDO = 'PMDB'
WHERE CODIGO_DO_MUNICIPIO = 38490

--21
UPDATE FiliadosPTC
SET SIGLA_DO_PARTIDO = 'PC'
WHERE NOME_DO_MUNICIPIO = 'SANTANÓPOLIS'

--22
UPDATE FiliadosPTC
SET SIGLA_DO_PARTIDO = 'PV', NOME_DO_PARTIDO = 'Partido Verde dos Filiados'
WHERE NOME_DO_MUNICIPIO = 'SÃO FÉLIX'

--23
UPDATE FiliadosPTC
SET SIGLA_DO_PARTIDO = 'PSDB', NOME_DO_PARTIDO = ' Partido da Social Democracia Brasileira'
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'

--24
UPDATE FiliadosPTC
SET NOME_DO_FILIADO = 'JORGE LUIS MAGALHÃES DOS SANTOS'
WHERE NOME_DO_FILIADO = 'JORGE LUIS FERREIRA DOS SANTOS'

--25
UPDATE FiliadosPTC
SET NOME_DO_FILIADO = 'RENATA XAVIER RODRIGUES'
WHERE NOME_DO_FILIADO = 'BENTA XAVIER RODRIGUES'

--26
UPDATE FiliadosPTC
SET NOME_DO_FILIADO = 'NOEL LEITE DA SILVA'
WHERE NOME_DO_FILIADO = 'NOE LEITE DA SILVA'

--27
UPDATE FiliadosPTC
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'JOSIENE ANDRADE DE SOUZA'

--28
UPDATE FiliadosPTC
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA'

--29
UPDATE FiliadosPTC
SET SITUACAO_DO_REGISTRO = 'DESFILIADO'
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA'

--30
ALTER TABLE FiliadosPTC
ADD Sexo CHAR(1);